exclude_paths:
  - tmp
  - vendor

detectors:
  LongParameterList:
    enabled: false
  NestedIterators:
    exclude:
      - "Infusible::Builder#define_initialize_with_keywords"
      - "Infusible::Builder#define_initialize_with_positionals"
      - "Infusible::Builder#define_new"

directories:
  "spec/lib/infusible":
    LongParameterList:
      enabled: false
