inherit_gem:
  caliber: config/all.yml

Lint/UselessMethodDefinition:
  Exclude:
    - "spec/lib/infusible/builder_spec.rb"

Metrics/ParameterLists:
  Exclude:
    - "spec/lib/infusible/builder_spec.rb"

Naming/VariableNumber:
  Exclude:
    - "spec/lib/infusible/dependency_map_spec.rb"
